/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.CommonImages

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID or Episode Number
 * @param title Episode Title
 * @param episode Episode Subtitle
 * @param url Episode Page URL
 * @param images
 */


data class AnimeVideosEpisodesAllOfData (

    /* MyAnimeList ID or Episode Number */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* Episode Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    /* Episode Subtitle */
    @get:JsonProperty("episode")
    val episode: kotlin.String? = null,

    /* Episode Page URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: CommonImages? = null

)
