/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Available Anime types
 *
 * Values: TV,MOVIE,OVA,SPECIAL,ONA,MUSIC,CM,PV,TV_SPECIAL
 */

enum class AnimeSearchQueryType(val value: kotlin.String) {

    @JsonProperty(value = "tv")
    TV("tv"),

    @JsonProperty(value = "movie")
    MOVIE("movie"),

    @JsonProperty(value = "ova")
    OVA("ova"),

    @JsonProperty(value = "special")
    SPECIAL("special"),

    @JsonProperty(value = "ona")
    ONA("ona"),

    @JsonProperty(value = "music")
    MUSIC("music"),

    @JsonProperty(value = "cm")
    CM("cm"),

    @JsonProperty(value = "pv")
    PV("pv"),

    @JsonProperty(value = "tv_special")
    TV_SPECIAL("tv_special");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AnimeSearchQueryType) "$data" else null

        /**
         * Returns a valid [AnimeSearchQueryType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AnimeSearchQueryType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
