/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Available Anime order_by properties
 *
 * Values: MAL_ID,TITLE,START_DATE,END_DATE,EPISODES,SCORE,SCORED_BY,RANK,POPULARITY,MEMBERS,FAVORITES
 */

enum class AnimeSearchQueryOrderby(val value: kotlin.String) {

    @JsonProperty(value = "mal_id")
    MAL_ID("mal_id"),

    @JsonProperty(value = "title")
    TITLE("title"),

    @JsonProperty(value = "start_date")
    START_DATE("start_date"),

    @JsonProperty(value = "end_date")
    END_DATE("end_date"),

    @JsonProperty(value = "episodes")
    EPISODES("episodes"),

    @JsonProperty(value = "score")
    SCORE("score"),

    @JsonProperty(value = "scored_by")
    SCORED_BY("scored_by"),

    @JsonProperty(value = "rank")
    RANK("rank"),

    @JsonProperty(value = "popularity")
    POPULARITY("popularity"),

    @JsonProperty(value = "members")
    MEMBERS("members"),

    @JsonProperty(value = "favorites")
    FAVORITES("favorites");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AnimeSearchQueryOrderby) "$data" else null

        /**
         * Returns a valid [AnimeSearchQueryOrderby] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AnimeSearchQueryOrderby? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
