/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeCharactersDataInnerVoiceActorsInnerPerson

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param person
 * @param language
 */


data class AnimeCharactersDataInnerVoiceActorsInner (

    @get:JsonProperty("person")
    val person: AnimeCharactersDataInnerVoiceActorsInnerPerson? = null,

    @get:JsonProperty("language")
    val language: kotlin.String? = null

)
