/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param openings
 * @param endings
 */


data class AnimeFullTheme (

    @get:JsonProperty("openings")
    val openings: kotlin.collections.List<kotlin.String>? = null,

    @get:JsonProperty("endings")
    val endings: kotlin.collections.List<kotlin.String>? = null

)
