/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeVideosDataMusicVideosInnerMeta
import com.jiktan.models.Trailer

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param title Title
 * @param video
 * @param meta
 */


data class AnimeVideosDataMusicVideosInner (

    /* Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    @get:JsonProperty("video")
    val video: Trailer? = null,

    @get:JsonProperty("meta")
    val meta: AnimeVideosDataMusicVideosInnerMeta? = null

)
