/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param title
 * @param author
 */


data class AnimeVideosDataMusicVideosInnerMeta (

    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    @get:JsonProperty("author")
    val author: kotlin.String? = null

)
