/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param score Scoring value
 * @param votes Number of votes for this score
 * @param percentage Percentage of votes for this score
 */


data class AnimeStatisticsDataScoresInner (

    /* Scoring value */
    @get:JsonProperty("score")
    val score: kotlin.Int? = null,

    /* Number of votes for this score */
    @get:JsonProperty("votes")
    val votes: kotlin.Int? = null,

    /* Percentage of votes for this score */
    @get:JsonProperty("percentage")
    val percentage: kotlin.Float? = null

)
