/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeVideosDataEpisodesInner
import com.jiktan.models.AnimeVideosDataMusicVideosInner
import com.jiktan.models.AnimeVideosDataPromoInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param promo
 * @param episodes
 * @param musicVideos
 */


data class AnimeVideosData (

    @get:JsonProperty("promo")
    val promo: kotlin.collections.List<AnimeVideosDataPromoInner>? = null,

    @get:JsonProperty("episodes")
    val episodes: kotlin.collections.List<AnimeVideosDataEpisodesInner>? = null,

    @get:JsonProperty("music_videos")
    val musicVideos: kotlin.collections.List<AnimeVideosDataMusicVideosInner>? = null

)
