/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL. This is the URL of the episode's video. If there is no video url, this will be null.
 * @param title Title
 * @param titleJapanese Title Japanese
 * @param titleRomanji title_romanji
 * @param aired Aired Date ISO8601
 * @param score Aggregated episode score (1.00 - 5.00) based on MyAnimeList user voting
 * @param filler Filler episode
 * @param recap Recap episode
 * @param forumUrl Episode discussion forum URL
 */


data class AnimeEpisodesAllOfData (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL. This is the URL of the episode's video. If there is no video url, this will be null. */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    /* Title Japanese */
    @get:JsonProperty("title_japanese")
    val titleJapanese: kotlin.String? = null,

    /* title_romanji */
    @get:JsonProperty("title_romanji")
    val titleRomanji: kotlin.String? = null,

    /* Aired Date ISO8601 */
    @get:JsonProperty("aired")
    val aired: kotlin.String? = null,

    /* Aggregated episode score (1.00 - 5.00) based on MyAnimeList user voting */
    @get:JsonProperty("score")
    val score: kotlin.Float? = null,

    /* Filler episode */
    @get:JsonProperty("filler")
    val filler: kotlin.Boolean? = null,

    /* Recap episode */
    @get:JsonProperty("recap")
    val recap: kotlin.Boolean? = null,

    /* Episode discussion forum URL */
    @get:JsonProperty("forum_url")
    val forumUrl: kotlin.String? = null

)
