/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeStatisticsDataScoresInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param watching Number of users watching the resource
 * @param completed Number of users who have completed the resource
 * @param onHold Number of users who have put the resource on hold
 * @param dropped Number of users who have dropped the resource
 * @param planToWatch Number of users who have planned to watch the resource
 * @param total Total number of users who have the resource added to their lists
 * @param scores
 */


data class AnimeStatisticsData (

    /* Number of users watching the resource */
    @get:JsonProperty("watching")
    val watching: kotlin.Int? = null,

    /* Number of users who have completed the resource */
    @get:JsonProperty("completed")
    val completed: kotlin.Int? = null,

    /* Number of users who have put the resource on hold */
    @get:JsonProperty("on_hold")
    val onHold: kotlin.Int? = null,

    /* Number of users who have dropped the resource */
    @get:JsonProperty("dropped")
    val dropped: kotlin.Int? = null,

    /* Number of users who have planned to watch the resource */
    @get:JsonProperty("plan_to_watch")
    val planToWatch: kotlin.Int? = null,

    /* Total number of users who have the resource added to their lists */
    @get:JsonProperty("total")
    val total: kotlin.Int? = null,

    @get:JsonProperty("scores")
    val scores: kotlin.collections.List<AnimeStatisticsDataScoresInner>? = null

)
