/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.Trailer

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param title Title
 * @param trailer
 */


data class AnimeVideosDataPromoInner (

    /* Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    @get:JsonProperty("trailer")
    val trailer: Trailer? = null

)
