/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeStaffDataInnerPerson

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param person
 * @param positions Staff Positions
 */


data class AnimeStaffDataInner (

    @get:JsonProperty("person")
    val person: AnimeStaffDataInnerPerson? = null,

    /* Staff Positions */
    @get:JsonProperty("positions")
    val positions: kotlin.collections.List<kotlin.String>? = null

)
