/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeCharactersDataInnerCharacter
import com.jiktan.models.AnimeCharactersDataInnerVoiceActorsInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param character
 * @param role Character's Role
 * @param voiceActors
 */


data class AnimeCharactersDataInner (

    @get:JsonProperty("character")
    val character: AnimeCharactersDataInnerCharacter? = null,

    /* Character's Role */
    @get:JsonProperty("role")
    val role: kotlin.String? = null,

    @get:JsonProperty("voice_actors")
    val voiceActors: kotlin.collections.List<AnimeCharactersDataInnerVoiceActorsInner>? = null

)
