/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Available Anime audience ratings<br><br><b>Ratings</b><br><ul><li>G - All Ages</li><li>PG - Children</li><li>PG-13 - Teens 13 or older</li><li>R - 17+ (violence & profanity)</li><li>R+ - Mild Nudity</li><li>Rx - Hentai</li></ul>
 *
 * Values: G,PG,PG13,R17,R,RX
 */

enum class AnimeSearchQueryRating(val value: kotlin.String) {

    @JsonProperty(value = "g")
    G("g"),

    @JsonProperty(value = "pg")
    PG("pg"),

    @JsonProperty(value = "pg13")
    PG13("pg13"),

    @JsonProperty(value = "r17")
    R17("r17"),

    @JsonProperty(value = "r")
    R("r"),

    @JsonProperty(value = "rx")
    RX("rx");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AnimeSearchQueryRating) "$data" else null

        /**
         * Returns a valid [AnimeSearchQueryRating] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AnimeSearchQueryRating? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
