/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param user
 * @param score User Score
 * @param status User list status
 * @param episodesSeen Number of episodes seen
 * @param episodesTotal Total number of episodes
 * @param date Last updated date ISO8601
 */


data class AnimeUserupdatesAllOfData (

    @get:JsonProperty("user")
    val user: UserMeta? = null,

    /* User Score */
    @get:JsonProperty("score")
    val score: kotlin.Int? = null,

    /* User list status */
    @get:JsonProperty("status")
    val status: kotlin.String? = null,

    /* Number of episodes seen */
    @get:JsonProperty("episodes_seen")
    val episodesSeen: kotlin.Int? = null,

    /* Total number of episodes */
    @get:JsonProperty("episodes_total")
    val episodesTotal: kotlin.Int? = null,

    /* Last updated date ISO8601 */
    @get:JsonProperty("date")
    val date: kotlin.String? = null

)
