/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param name
 * @param url
 */


data class AnimeFullExternalInner (

    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @get:JsonProperty("url")
    val url: kotlin.String? = null

)
