/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Available images in JPG
 *
 * @param imageUrl Image URL JPG
 * @param smallImageUrl Small Image URL JPG
 * @param largeImageUrl Image URL JPG
 */


data class AnimeImagesJpg (

    /* Image URL JPG */
    @get:JsonProperty("image_url")
    val imageUrl: kotlin.String? = null,

    /* Small Image URL JPG */
    @get:JsonProperty("small_image_url")
    val smallImageUrl: kotlin.String? = null,

    /* Image URL JPG */
    @get:JsonProperty("large_image_url")
    val largeImageUrl: kotlin.String? = null

)
