/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Broadcast Details
 *
 * @param day Day of the week
 * @param time Time in 24 hour format
 * @param timezone Timezone (Tz Database format https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
 * @param string Raw parsed broadcast string
 */


data class Broadcast (

    /* Day of the week */
    @get:JsonProperty("day")
    val day: kotlin.String? = null,

    /* Time in 24 hour format */
    @get:JsonProperty("time")
    val time: kotlin.String? = null,

    /* Timezone (Tz Database format https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) */
    @get:JsonProperty("timezone")
    val timezone: kotlin.String? = null,

    /* Raw parsed broadcast string */
    @get:JsonProperty("string")
    val string: kotlin.String? = null

)
