/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.PersonMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param language Character's Role
 * @param person
 */


data class CharacterFullVoicesInner (

    /* Character's Role */
    @get:JsonProperty("language")
    val language: kotlin.String? = null,

    @get:JsonProperty("person")
    val person: PersonMeta? = null

)
