/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param imageUrl Default JPG Image Size URL
 * @param largeImageUrl Large JPG Image Size URL
 */


data class CharacterPicturesDataInner (

    /* Default JPG Image Size URL */
    @get:JsonProperty("image_url")
    val imageUrl: kotlin.String? = null,

    /* Large JPG Image Size URL */
    @get:JsonProperty("large_image_url")
    val largeImageUrl: kotlin.String? = null

)
