/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.CharacterAnimeDataInner
import com.jiktan.models.CharacterFullMangaInner
import com.jiktan.models.CharacterFullVoicesInner
import com.jiktan.models.CharacterImages

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Character Resource
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param images
 * @param name Name
 * @param nameKanji Name
 * @param nicknames Other Names
 * @param favorites Number of users who have favorited this entry
 * @param about Biography
 * @param anime
 * @param manga
 * @param voices
 */


data class CharacterFull (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: CharacterImages? = null,

    /* Name */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Name */
    @get:JsonProperty("name_kanji")
    val nameKanji: kotlin.String? = null,

    /* Other Names */
    @get:JsonProperty("nicknames")
    val nicknames: kotlin.collections.List<kotlin.String>? = null,

    /* Number of users who have favorited this entry */
    @get:JsonProperty("favorites")
    val favorites: kotlin.Int? = null,

    /* Biography */
    @get:JsonProperty("about")
    val about: kotlin.String? = null,

    @get:JsonProperty("anime")
    val anime: kotlin.collections.List<CharacterAnimeDataInner>? = null,

    @get:JsonProperty("manga")
    val manga: kotlin.collections.List<CharacterFullMangaInner>? = null,

    @get:JsonProperty("voices")
    val voices: kotlin.collections.List<CharacterFullVoicesInner>? = null

)
