/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Available images in WEBP
 *
 * @param imageUrl Image URL WEBP
 * @param smallImageUrl Small Image URL WEBP
 */


data class CharacterImagesWebp (

    /* Image URL WEBP */
    @get:JsonProperty("image_url")
    val imageUrl: kotlin.String? = null,

    /* Small Image URL WEBP */
    @get:JsonProperty("small_image_url")
    val smallImageUrl: kotlin.String? = null

)
