/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param role Character's Role
 * @param anime
 */


data class CharacterAnimeDataInner (

    /* Character's Role */
    @get:JsonProperty("role")
    val role: kotlin.String? = null,

    @get:JsonProperty("anime")
    val anime: AnimeMeta? = null

)
