/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param url User URL
 * @param username User's username
 */


data class ClubStaffDataInner (

    /* User URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* User's username */
    @get:JsonProperty("username")
    val username: kotlin.String? = null

)
