/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Club Search Query Type
 *
 * Values: PUBLIC,PRIVATE,SECRET
 */

enum class ClubSearchQueryType(val value: kotlin.String) {

    @JsonProperty(value = "public")
    PUBLIC("public"),

    @JsonProperty(value = "private")
    PRIVATE("private"),

    @JsonProperty(value = "secret")
    SECRET("secret");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ClubSearchQueryType) "$data" else null

        /**
         * Returns a valid [ClubSearchQueryType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ClubSearchQueryType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
