/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.MalUrl

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param anime
 * @param manga
 * @param characters
 */


data class ClubRelationsData (

    @get:JsonProperty("anime")
    val anime: kotlin.collections.List<MalUrl>? = null,

    @get:JsonProperty("manga")
    val manga: kotlin.collections.List<MalUrl>? = null,

    @get:JsonProperty("characters")
    val characters: kotlin.collections.List<MalUrl>? = null

)
