/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Date Prop To
 *
 * @param day Day
 * @param month Month
 * @param year Year
 */


data class DaterangePropTo (

    /* Day */
    @get:JsonProperty("day")
    val day: kotlin.Int? = null,

    /* Month */
    @get:JsonProperty("month")
    val month: kotlin.Int? = null,

    /* Year */
    @get:JsonProperty("year")
    val year: kotlin.Int? = null

)
