/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.DaterangeProp

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Date range
 *
 * @param from Date ISO8601
 * @param to Date ISO8601
 * @param prop
 */


data class Daterange (

    /* Date ISO8601 */
    @get:JsonProperty("from")
    val from: kotlin.String? = null,

    /* Date ISO8601 */
    @get:JsonProperty("to")
    val to: kotlin.String? = null,

    @get:JsonProperty("prop")
    val prop: DaterangeProp? = null

)
