/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.DaterangePropFrom
import com.jiktan.models.DaterangePropTo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Date Prop
 *
 * @param from
 * @param to
 * @param string Raw parsed string
 */


data class DaterangeProp (

    @get:JsonProperty("from")
    val from: DaterangePropFrom? = null,

    @get:JsonProperty("to")
    val to: DaterangePropTo? = null,

    /* Raw parsed string */
    @get:JsonProperty("string")
    val string: kotlin.String? = null

)
