/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Entry Recommendations Resource
 *
 * @param `data`
 */


data class EntryRecommendations (

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<kotlin.Any>? = null

)
