/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Entry Meta data
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param imageUrl Image URL
 * @param name Entry Name/Title
 */


data class EntryMeta (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Image URL */
    @get:JsonProperty("image_url")
    val imageUrl: kotlin.String? = null,

    /* Entry Name/Title */
    @get:JsonProperty("name")
    val name: kotlin.String? = null

)
