/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Last comment details
 *
 * @param url Last comment URL
 * @param authorUsername Author MyAnimeList Username
 * @param authorUrl Author Profile URL
 * @param date Last comment date posted ISO8601
 */


data class ForumDataInnerLastComment (

    /* Last comment URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Author MyAnimeList Username */
    @get:JsonProperty("author_username")
    val authorUsername: kotlin.String? = null,

    /* Author Profile URL */
    @get:JsonProperty("author_url")
    val authorUrl: kotlin.String? = null,

    /* Last comment date posted ISO8601 */
    @get:JsonProperty("date")
    val date: kotlin.String? = null

)
