/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.ForumDataInnerLastComment

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param title Title
 * @param date Post Date ISO8601
 * @param authorUsername Author MyAnimeList Username
 * @param authorUrl Author Profile URL
 * @param comments Comment count
 * @param lastComment
 */


data class ForumDataInner (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    /* Post Date ISO8601 */
    @get:JsonProperty("date")
    val date: kotlin.String? = null,

    /* Author MyAnimeList Username */
    @get:JsonProperty("author_username")
    val authorUsername: kotlin.String? = null,

    /* Author Profile URL */
    @get:JsonProperty("author_url")
    val authorUrl: kotlin.String? = null,

    /* Comment count */
    @get:JsonProperty("comments")
    val comments: kotlin.Int? = null,

    @get:JsonProperty("last_comment")
    val lastComment: ForumDataInnerLastComment? = null

)
