/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Genre Resource
 *
 * @param malId MyAnimeList ID
 * @param name Genre Name
 * @param url MyAnimeList URL
 * @param count Genre's entry count
 */


data class Genre (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* Genre Name */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Genre's entry count */
    @get:JsonProperty("count")
    val count: kotlin.Int? = null

)
