/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Filter genres by type
 *
 * Values: GENRES,EXPLICIT_GENRES,THEMES,DEMOGRAPHICS
 */

enum class GenreQueryFilter(val value: kotlin.String) {

    @JsonProperty(value = "genres")
    GENRES("genres"),

    @JsonProperty(value = "explicit_genres")
    EXPLICIT_GENRES("explicit_genres"),

    @JsonProperty(value = "themes")
    THEMES("themes"),

    @JsonProperty(value = "demographics")
    DEMOGRAPHICS("demographics");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is GenreQueryFilter) "$data" else null

        /**
         * Returns a valid [GenreQueryFilter] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): GenreQueryFilter? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
