/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.Club

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param `data`
 */


data class GetClubsById200Response (

    @get:JsonProperty("data")
    val `data`: Club? = null

)
