/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeMeta
import com.jiktan.models.GetTopReviews200ResponseDataAllOfDataInnerAnyOf
import com.jiktan.models.GetTopReviews200ResponseDataAllOfDataInnerAnyOf1
import com.jiktan.models.MangaMeta
import com.jiktan.models.MangaReviewReactions
import com.jiktan.models.UserMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param user
 * @param anime
 * @param malId MyAnimeList ID
 * @param url MyAnimeList review URL
 * @param type Entry type
 * @param reactions
 * @param date Review created date ISO8601
 * @param review Review content
 * @param score Number of user votes on the Review
 * @param tags Review tags
 * @param isSpoiler The review contains spoiler
 * @param isPreliminary The review was made before the entry was completed
 * @param episodesWatched Number of episodes watched
 * @param manga
 */


data class GetTopReviews200ResponseDataAllOfDataInner (

    @get:JsonProperty("user")
    val user: UserMeta? = null,

    @get:JsonProperty("anime")
    val anime: AnimeMeta? = null,

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList review URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Entry type */
    @get:JsonProperty("type")
    val type: kotlin.String? = null,

    @get:JsonProperty("reactions")
    val reactions: MangaReviewReactions? = null,

    /* Review created date ISO8601 */
    @get:JsonProperty("date")
    val date: kotlin.String? = null,

    /* Review content */
    @get:JsonProperty("review")
    val review: kotlin.String? = null,

    /* Number of user votes on the Review */
    @get:JsonProperty("score")
    val score: kotlin.Int? = null,

    /* Review tags */
    @get:JsonProperty("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    /* The review contains spoiler */
    @get:JsonProperty("is_spoiler")
    val isSpoiler: kotlin.Boolean? = null,

    /* The review was made before the entry was completed */
    @get:JsonProperty("is_preliminary")
    val isPreliminary: kotlin.Boolean? = null,

    /* Number of episodes watched */
    @get:JsonProperty("episodes_watched")
    val episodesWatched: kotlin.Int? = null,

    @get:JsonProperty("manga")
    val manga: MangaMeta? = null

)
