/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.MalUrl

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Transform the resource into an array.
 *
 * @param entry
 * @param increment Number of episodes/chapters watched/read
 * @param date Date ISO8601
 */


data class History (

    @get:JsonProperty("entry")
    val entry: MalUrl? = null,

    /* Number of episodes/chapters watched/read */
    @get:JsonProperty("increment")
    val increment: kotlin.Int? = null,

    /* Date ISO8601 */
    @get:JsonProperty("date")
    val date: kotlin.String? = null

)
