/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Parsed URL Data
 *
 * @param malId MyAnimeList ID
 * @param type Type of resource
 * @param title Resource Name/Title
 * @param url MyAnimeList URL
 */


data class MalUrl2 (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* Type of resource */
    @get:JsonProperty("type")
    val type: kotlin.String? = null,

    /* Resource Name/Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null

)
