/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.MangaCharactersDataInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Manga Characters Resource
 *
 * @param `data`
 */


data class MangaCharacters (

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<MangaCharactersDataInner>? = null

)
