/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.CharacterMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param character
 * @param role Character's Role
 */


data class MangaCharactersDataInner (

    @get:JsonProperty("character")
    val character: CharacterMeta? = null,

    /* Character's Role */
    @get:JsonProperty("role")
    val role: kotlin.String? = null

)
