/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * User reaction count on the review
 *
 * @param overall Overall reaction count
 * @param nice Nice reaction count
 * @param loveIt Love it reaction count
 * @param funny Funny reaction count
 * @param confusing Confusing reaction count
 * @param informative Informative reaction count
 * @param wellWritten Well written reaction count
 * @param creative Creative reaction count
 */


data class MangaReviewReactions (

    /* Overall reaction count */
    @get:JsonProperty("overall")
    val overall: kotlin.Int? = null,

    /* Nice reaction count */
    @get:JsonProperty("nice")
    val nice: kotlin.Int? = null,

    /* Love it reaction count */
    @get:JsonProperty("love_it")
    val loveIt: kotlin.Int? = null,

    /* Funny reaction count */
    @get:JsonProperty("funny")
    val funny: kotlin.Int? = null,

    /* Confusing reaction count */
    @get:JsonProperty("confusing")
    val confusing: kotlin.Int? = null,

    /* Informative reaction count */
    @get:JsonProperty("informative")
    val informative: kotlin.Int? = null,

    /* Well written reaction count */
    @get:JsonProperty("well_written")
    val wellWritten: kotlin.Int? = null,

    /* Creative reaction count */
    @get:JsonProperty("creative")
    val creative: kotlin.Int? = null

)
