/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.MangaReviewsAllOfDataInner
import com.jiktan.models.PaginationPagination

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Manga Reviews Resource
 *
 * @param pagination
 * @param `data`
 */


data class MangaReviews (

    @get:JsonProperty("pagination")
    val pagination: PaginationPagination? = null,

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<MangaReviewsAllOfDataInner>? = null

)
