/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.MangaStatisticsData

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Manga Statistics Resource
 *
 * @param `data`
 */


data class MangaStatistics (

    @get:JsonProperty("data")
    val `data`: MangaStatisticsData? = null

)
