/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param user
 * @param score User Score
 * @param status User list status
 * @param volumesRead Number of volumes read
 * @param volumesTotal Total number of volumes
 * @param chaptersRead Number of chapters read
 * @param chaptersTotal Total number of chapters
 * @param date Last updated date ISO8601
 */


data class MangaUserupdatesAllOfData (

    @get:JsonProperty("user")
    val user: UserMeta? = null,

    /* User Score */
    @get:JsonProperty("score")
    val score: kotlin.Int? = null,

    /* User list status */
    @get:JsonProperty("status")
    val status: kotlin.String? = null,

    /* Number of volumes read */
    @get:JsonProperty("volumes_read")
    val volumesRead: kotlin.Int? = null,

    /* Total number of volumes */
    @get:JsonProperty("volumes_total")
    val volumesTotal: kotlin.Int? = null,

    /* Number of chapters read */
    @get:JsonProperty("chapters_read")
    val chaptersRead: kotlin.Int? = null,

    /* Total number of chapters */
    @get:JsonProperty("chapters_total")
    val chaptersTotal: kotlin.Int? = null,

    /* Last updated date ISO8601 */
    @get:JsonProperty("date")
    val date: kotlin.String? = null

)
