/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param moreinfo Additional information on the entry
 */


data class MoreinfoData (

    /* Additional information on the entry */
    @get:JsonProperty("moreinfo")
    val moreinfo: kotlin.String? = null

)
