/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.NewsDataInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param `data`
 */


data class News (

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<NewsDataInner>? = null

)
