/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.PaginationPlusPaginationItems

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param lastVisiblePage
 * @param hasNextPage
 * @param currentPage
 * @param items
 */


data class PaginationPlusPagination (

    @get:JsonProperty("last_visible_page")
    val lastVisiblePage: kotlin.Int? = null,

    @get:JsonProperty("has_next_page")
    val hasNextPage: kotlin.Boolean? = null,

    @get:JsonProperty("current_page")
    val currentPage: kotlin.Int? = null,

    @get:JsonProperty("items")
    val items: PaginationPlusPaginationItems? = null

)
