/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param lastVisiblePage
 * @param hasNextPage
 */


data class PaginationPagination (

    @get:JsonProperty("last_visible_page")
    val lastVisiblePage: kotlin.Int? = null,

    @get:JsonProperty("has_next_page")
    val hasNextPage: kotlin.Boolean? = null

)
