/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param count
 * @param total
 * @param perPage
 */


data class PaginationPlusPaginationItems (

    @get:JsonProperty("count")
    val count: kotlin.Int? = null,

    @get:JsonProperty("total")
    val total: kotlin.Int? = null,

    @get:JsonProperty("per_page")
    val perPage: kotlin.Int? = null

)
