/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.PaginationPagination

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param pagination
 */


data class Pagination (

    @get:JsonProperty("pagination")
    val pagination: PaginationPagination? = null

)
