/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Available People order_by properties
 *
 * Values: MAL_ID,NAME,BIRTHDAY,FAVORITES
 */

enum class PeopleSearchQueryOrderby(val value: kotlin.String) {

    @JsonProperty(value = "mal_id")
    MAL_ID("mal_id"),

    @JsonProperty(value = "name")
    NAME("name"),

    @JsonProperty(value = "birthday")
    BIRTHDAY("birthday"),

    @JsonProperty(value = "favorites")
    FAVORITES("favorites");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PeopleSearchQueryOrderby) "$data" else null

        /**
         * Returns a valid [PeopleSearchQueryOrderby] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PeopleSearchQueryOrderby? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
