/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.PaginationPlusPagination
import com.jiktan.models.PeopleSearchAllOfData

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * People Search
 *
 * @param pagination
 * @param `data`
 */


data class PeopleSearch (

    @get:JsonProperty("pagination")
    val pagination: PaginationPlusPagination? = null,

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<PeopleSearchAllOfData>? = null

)
