/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.PeopleImages
import com.jiktan.models.PersonAnimeDataInner
import com.jiktan.models.PersonFullMangaInner
import com.jiktan.models.PersonFullVoicesInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Person Resource
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param websiteUrl Person's website URL
 * @param images
 * @param name Name
 * @param givenName Given Name
 * @param familyName Family Name
 * @param alternateNames Other Names
 * @param birthday Birthday Date ISO8601
 * @param favorites Number of users who have favorited this entry
 * @param about Biography
 * @param anime
 * @param manga
 * @param voices
 */


data class PersonFull (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Person's website URL */
    @get:JsonProperty("website_url")
    val websiteUrl: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: PeopleImages? = null,

    /* Name */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Given Name */
    @get:JsonProperty("given_name")
    val givenName: kotlin.String? = null,

    /* Family Name */
    @get:JsonProperty("family_name")
    val familyName: kotlin.String? = null,

    /* Other Names */
    @get:JsonProperty("alternate_names")
    val alternateNames: kotlin.collections.List<kotlin.String>? = null,

    /* Birthday Date ISO8601 */
    @get:JsonProperty("birthday")
    val birthday: kotlin.String? = null,

    /* Number of users who have favorited this entry */
    @get:JsonProperty("favorites")
    val favorites: kotlin.Int? = null,

    /* Biography */
    @get:JsonProperty("about")
    val about: kotlin.String? = null,

    @get:JsonProperty("anime")
    val anime: kotlin.collections.List<PersonAnimeDataInner>? = null,

    @get:JsonProperty("manga")
    val manga: kotlin.collections.List<PersonFullMangaInner>? = null,

    @get:JsonProperty("voices")
    val voices: kotlin.collections.List<PersonFullVoicesInner>? = null

)
