/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeMeta
import com.jiktan.models.CharacterMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param role Person's Character's role in the anime
 * @param anime
 * @param character
 */


data class PersonFullVoicesInner (

    /* Person's Character's role in the anime */
    @get:JsonProperty("role")
    val role: kotlin.String? = null,

    @get:JsonProperty("anime")
    val anime: AnimeMeta? = null,

    @get:JsonProperty("character")
    val character: CharacterMeta? = null

)
