/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param position Person's position
 * @param anime
 */


data class PersonAnimeDataInner (

    /* Person's position */
    @get:JsonProperty("position")
    val position: kotlin.String? = null,

    @get:JsonProperty("anime")
    val anime: AnimeMeta? = null

)
