/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.PeopleImages

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param images
 * @param name Entry name
 */


data class PersonMeta (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: PeopleImages? = null,

    /* Entry name */
    @get:JsonProperty("name")
    val name: kotlin.String? = null

)
