/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.CommonImages

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param images
 */


data class PicturesVariantsDataInner (

    @get:JsonProperty("images")
    val images: CommonImages? = null

)
