/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeFullExternalInner
import com.jiktan.models.CommonImages
import com.jiktan.models.Title

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Producers Resource
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param titles All titles
 * @param images
 * @param favorites Producers's member favorites count
 * @param count Producers's anime count
 * @param established Established Date ISO8601
 * @param about About the Producer
 * @param `external`
 */


data class ProducerFull (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* All titles */
    @get:JsonProperty("titles")
    val titles: kotlin.collections.List<Title>? = null,

    @get:JsonProperty("images")
    val images: CommonImages? = null,

    /* Producers's member favorites count */
    @get:JsonProperty("favorites")
    val favorites: kotlin.Int? = null,

    /* Producers's anime count */
    @get:JsonProperty("count")
    val count: kotlin.Int? = null,

    /* Established Date ISO8601 */
    @get:JsonProperty("established")
    val established: kotlin.String? = null,

    /* About the Producer */
    @get:JsonProperty("about")
    val about: kotlin.String? = null,

    @get:JsonProperty("external")
    val `external`: kotlin.collections.List<AnimeFullExternalInner>? = null

)
