/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Producers Search Query Order By
 *
 * Values: MAL_ID,COUNT,FAVORITES,ESTABLISHED
 */

enum class ProducersQueryOrderby(val value: kotlin.String) {

    @JsonProperty(value = "mal_id")
    MAL_ID("mal_id"),

    @JsonProperty(value = "count")
    COUNT("count"),

    @JsonProperty(value = "favorites")
    FAVORITES("favorites"),

    @JsonProperty(value = "established")
    ESTABLISHED("established");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ProducersQueryOrderby) "$data" else null

        /**
         * Returns a valid [ProducersQueryOrderby] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ProducersQueryOrderby? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
