/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserById

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MAL IDs of recommendations is both of the MAL ID's with a `-` delimiter
 * @param entry Array of 2 entries that are being recommended to each other
 * @param content Recommendation context provided by the user
 * @param user
 */


data class RecommendationsAllOfData (

    /* MAL IDs of recommendations is both of the MAL ID's with a `-` delimiter */
    @get:JsonProperty("mal_id")
    val malId: kotlin.String? = null,

    /* Array of 2 entries that are being recommended to each other */
    @get:JsonProperty("entry")
    val entry: kotlin.collections.List<Any?>? = null,

    /* Recommendation context provided by the user */
    @get:JsonProperty("content")
    val content: kotlin.String? = null,

    @get:JsonProperty("user")
    val user: UserById? = null

)
