/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.MalUrl

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Related resources
 *
 * @param relation Relation type
 * @param entry Related entries
 */


data class Relation (

    /* Relation type */
    @get:JsonProperty("relation")
    val relation: kotlin.String? = null,

    /* Related entries */
    @get:JsonProperty("entry")
    val entry: kotlin.collections.List<MalUrl>? = null

)
