/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.Anime
import com.jiktan.models.PaginationPlusPagination

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Anime resources currently airing
 *
 * @param pagination
 * @param `data`
 */


data class Schedules (

    @get:JsonProperty("pagination")
    val pagination: PaginationPlusPagination? = null,

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<Anime>? = null

)
