/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param year Year
 * @param seasons List of available seasons
 */


data class SeasonsDataInner (

    /* Year */
    @get:JsonProperty("year")
    val year: kotlin.Int? = null,

    /* List of available seasons */
    @get:JsonProperty("seasons")
    val seasons: kotlin.collections.List<kotlin.String>? = null

)
