/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param type Title type
 * @param title Title value
 */


data class Title (

    /* Title type */
    @get:JsonProperty("type")
    val type: kotlin.String? = null,

    /* Title value */
    @get:JsonProperty("title")
    val title: kotlin.String? = null

)
