/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Top items filter types
 *
 * Values: AIRING,UPCOMING,BYPOPULARITY,FAVORITE
 */

enum class TopAnimeFilter(val value: kotlin.String) {

    @JsonProperty(value = "airing")
    AIRING("airing"),

    @JsonProperty(value = "upcoming")
    UPCOMING("upcoming"),

    @JsonProperty(value = "bypopularity")
    BYPOPULARITY("bypopularity"),

    @JsonProperty(value = "favorite")
    FAVORITE("favorite");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TopAnimeFilter) "$data" else null

        /**
         * Returns a valid [TopAnimeFilter] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TopAnimeFilter? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
