/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Youtube Details
 *
 * @param youtubeId YouTube ID
 * @param url YouTube URL
 * @param embedUrl Parsed Embed URL
 */


data class TrailerBase (

    /* YouTube ID */
    @get:JsonProperty("youtube_id")
    val youtubeId: kotlin.String? = null,

    /* YouTube URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Parsed Embed URL */
    @get:JsonProperty("embed_url")
    val embedUrl: kotlin.String? = null

)
