/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * User Meta By ID
 *
 * @param url MyAnimeList URL
 * @param username MyAnimeList Username
 */


data class UserById (

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* MyAnimeList Username */
    @get:JsonProperty("username")
    val username: kotlin.String? = null

)
