/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Anime Statistics
 *
 * @param daysWatched Number of days spent watching Anime
 * @param meanScore Mean Score
 * @param watching Anime Watching
 * @param completed Anime Completed
 * @param onHold Anime On-Hold
 * @param dropped Anime Dropped
 * @param planToWatch Anime Planned to Watch
 * @param totalEntries Total Anime entries on User list
 * @param rewatched Anime re-watched
 * @param episodesWatched Number of Anime Episodes Watched
 */


data class UserProfileFullStatisticsAnime (

    /* Number of days spent watching Anime */
    @get:JsonProperty("days_watched")
    val daysWatched: kotlin.Float? = null,

    /* Mean Score */
    @get:JsonProperty("mean_score")
    val meanScore: kotlin.Float? = null,

    /* Anime Watching */
    @get:JsonProperty("watching")
    val watching: kotlin.Int? = null,

    /* Anime Completed */
    @get:JsonProperty("completed")
    val completed: kotlin.Int? = null,

    /* Anime On-Hold */
    @get:JsonProperty("on_hold")
    val onHold: kotlin.Int? = null,

    /* Anime Dropped */
    @get:JsonProperty("dropped")
    val dropped: kotlin.Int? = null,

    /* Anime Planned to Watch */
    @get:JsonProperty("plan_to_watch")
    val planToWatch: kotlin.Int? = null,

    /* Total Anime entries on User list */
    @get:JsonProperty("total_entries")
    val totalEntries: kotlin.Int? = null,

    /* Anime re-watched */
    @get:JsonProperty("rewatched")
    val rewatched: kotlin.Int? = null,

    /* Number of Anime Episodes Watched */
    @get:JsonProperty("episodes_watched")
    val episodesWatched: kotlin.Int? = null

)
