/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.MangaMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param entry
 * @param score
 * @param status
 * @param chaptersRead
 * @param chaptersTotal
 * @param volumesRead
 * @param volumesTotal
 * @param date ISO8601 format
 */


data class UserUpdatesDataMangaInner (

    @get:JsonProperty("entry")
    val entry: MangaMeta? = null,

    @get:JsonProperty("score")
    val score: kotlin.Int? = null,

    @get:JsonProperty("status")
    val status: kotlin.String? = null,

    @get:JsonProperty("chapters_read")
    val chaptersRead: kotlin.Int? = null,

    @get:JsonProperty("chapters_total")
    val chaptersTotal: kotlin.Int? = null,

    @get:JsonProperty("volumes_read")
    val volumesRead: kotlin.Int? = null,

    @get:JsonProperty("volumes_total")
    val volumesTotal: kotlin.Int? = null,

    /* ISO8601 format */
    @get:JsonProperty("date")
    val date: kotlin.String? = null

)
