/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserProfileFullStatisticsAnime
import com.jiktan.models.UserProfileFullStatisticsManga

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param anime
 * @param manga
 */


data class UserProfileFullStatistics (

    @get:JsonProperty("anime")
    val anime: UserProfileFullStatisticsAnime? = null,

    @get:JsonProperty("manga")
    val manga: UserProfileFullStatisticsManga? = null

)
