/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.CharacterMeta
import com.jiktan.models.UserFavoritesAnimeInner
import com.jiktan.models.UserFavoritesCharactersInner
import com.jiktan.models.UserFavoritesMangaInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param anime Favorite Anime
 * @param manga Favorite Manga
 * @param characters Favorite Characters
 * @param people Favorite People
 */


data class UserFavorites (

    /* Favorite Anime */
    @get:JsonProperty("anime")
    val anime: kotlin.collections.List<UserFavoritesAnimeInner>? = null,

    /* Favorite Manga */
    @get:JsonProperty("manga")
    val manga: kotlin.collections.List<UserFavoritesMangaInner>? = null,

    /* Favorite Characters */
    @get:JsonProperty("characters")
    val characters: kotlin.collections.List<UserFavoritesCharactersInner>? = null,

    /* Favorite People */
    @get:JsonProperty("people")
    val people: kotlin.collections.List<CharacterMeta>? = null

)
