/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserImages

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param url MyAnimeList URL
 * @param username MyAnimeList Username
 * @param images
 * @param lastOnline Last Online Date ISO8601
 */


data class UsersSearchAllOfData (

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* MyAnimeList Username */
    @get:JsonProperty("username")
    val username: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: UserImages? = null,

    /* Last Online Date ISO8601 */
    @get:JsonProperty("last_online")
    val lastOnline: kotlin.String? = null

)
