/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UsersTempDataInnerImagesJpg
import com.jiktan.models.UsersTempDataInnerImagesWebp

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Images
 *
 * @param jpg
 * @param webp
 */


data class UsersTempDataInnerImages (

    @get:JsonProperty("jpg")
    val jpg: UsersTempDataInnerImagesJpg? = null,

    @get:JsonProperty("webp")
    val webp: UsersTempDataInnerImagesWebp? = null

)
