/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param user
 * @param lastOnline Last Online Date ISO8601 format
 * @param friendsSince Friends Since Date ISO8601 format
 */


data class UserFriendsAllOfDataInner (

    @get:JsonProperty("user")
    val user: UserMeta? = null,

    /* Last Online Date ISO8601 format */
    @get:JsonProperty("last_online")
    val lastOnline: kotlin.String? = null,

    /* Friends Since Date ISO8601 format */
    @get:JsonProperty("friends_since")
    val friendsSince: kotlin.String? = null

)
