/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID
 * @param name Club Name
 * @param url Club URL
 */


data class UserClubsAllOfData (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* Club Name */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Club URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null

)
