/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UsersTempDataInnerAnimeStats
import com.jiktan.models.UsersTempDataInnerFavorites
import com.jiktan.models.UsersTempDataInnerImages
import com.jiktan.models.UsersTempDataInnerMangaStats

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID
 * @param username MyAnimeList Username
 * @param url MyAnimeList URL
 * @param images
 * @param lastOnline Last Online Date ISO8601
 * @param gender User Gender
 * @param birthday Birthday Date ISO8601
 * @param location Location
 * @param joined Joined Date ISO8601
 * @param animeStats
 * @param mangaStats
 * @param favorites
 * @param about User About. NOTE: About information is customizable by users through BBCode on MyAnimeList. This means users can add multimedia content, different text sizes, etc. Due to this freeform, Jikan returns parsed HTML. Validate on your end!
 */


data class UsersTempDataInner (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList Username */
    @get:JsonProperty("username")
    val username: kotlin.String? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: UsersTempDataInnerImages? = null,

    /* Last Online Date ISO8601 */
    @get:JsonProperty("last_online")
    val lastOnline: kotlin.String? = null,

    /* User Gender */
    @get:JsonProperty("gender")
    val gender: kotlin.String? = null,

    /* Birthday Date ISO8601 */
    @get:JsonProperty("birthday")
    val birthday: kotlin.String? = null,

    /* Location */
    @get:JsonProperty("location")
    val location: kotlin.String? = null,

    /* Joined Date ISO8601 */
    @get:JsonProperty("joined")
    val joined: kotlin.String? = null,

    @get:JsonProperty("anime_stats")
    val animeStats: UsersTempDataInnerAnimeStats? = null,

    @get:JsonProperty("manga_stats")
    val mangaStats: UsersTempDataInnerMangaStats? = null,

    @get:JsonProperty("favorites")
    val favorites: UsersTempDataInnerFavorites? = null,

    /* User About. NOTE: About information is customizable by users through BBCode on MyAnimeList. This means users can add multimedia content, different text sizes, etc. Due to this freeform, Jikan returns parsed HTML. Validate on your end! */
    @get:JsonProperty("about")
    val about: kotlin.String? = null

)
