/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * User's anime list status filter options
 *
 * Values: ALL,READING,COMPLETED,ONHOLD,DROPPED,PLANTOREAD
 */

enum class UserMangaListStatusFilter(val value: kotlin.String) {

    @JsonProperty(value = "all")
    ALL("all"),

    @JsonProperty(value = "reading")
    READING("reading"),

    @JsonProperty(value = "completed")
    COMPLETED("completed"),

    @JsonProperty(value = "onhold")
    ONHOLD("onhold"),

    @JsonProperty(value = "dropped")
    DROPPED("dropped"),

    @JsonProperty(value = "plantoread")
    PLANTOREAD("plantoread");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UserMangaListStatusFilter) "$data" else null

        /**
         * Returns a valid [UserMangaListStatusFilter] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UserMangaListStatusFilter? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
