/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Manga Statistics
 *
 * @param daysRead Number of days spent reading Manga
 * @param meanScore Mean Score
 * @param reading Manga Reading
 * @param completed Manga Completed
 * @param onHold Manga On-Hold
 * @param dropped Manga Dropped
 * @param planToRead Manga Planned to Read
 * @param totalEntries Total Manga entries on User list
 * @param reread Manga re-read
 * @param chaptersRead Number of Manga Chapters Read
 * @param volumesRead Number of Manga Volumes Read
 */


data class UserProfileFullStatisticsManga (

    /* Number of days spent reading Manga */
    @get:JsonProperty("days_read")
    val daysRead: kotlin.Float? = null,

    /* Mean Score */
    @get:JsonProperty("mean_score")
    val meanScore: kotlin.Float? = null,

    /* Manga Reading */
    @get:JsonProperty("reading")
    val reading: kotlin.Int? = null,

    /* Manga Completed */
    @get:JsonProperty("completed")
    val completed: kotlin.Int? = null,

    /* Manga On-Hold */
    @get:JsonProperty("on_hold")
    val onHold: kotlin.Int? = null,

    /* Manga Dropped */
    @get:JsonProperty("dropped")
    val dropped: kotlin.Int? = null,

    /* Manga Planned to Read */
    @get:JsonProperty("plan_to_read")
    val planToRead: kotlin.Int? = null,

    /* Total Manga entries on User list */
    @get:JsonProperty("total_entries")
    val totalEntries: kotlin.Int? = null,

    /* Manga re-read */
    @get:JsonProperty("reread")
    val reread: kotlin.Int? = null,

    /* Number of Manga Chapters Read */
    @get:JsonProperty("chapters_read")
    val chaptersRead: kotlin.Int? = null,

    /* Number of Manga Volumes Read */
    @get:JsonProperty("volumes_read")
    val volumesRead: kotlin.Int? = null

)
