/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserUpdatesDataAnimeInner
import com.jiktan.models.UserUpdatesDataMangaInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param anime Last updated Anime
 * @param manga Last updated Manga
 */


data class UserUpdatesData (

    /* Last updated Anime */
    @get:JsonProperty("anime")
    val anime: kotlin.collections.List<UserUpdatesDataAnimeInner>? = null,

    /* Last updated Manga */
    @get:JsonProperty("manga")
    val manga: kotlin.collections.List<UserUpdatesDataMangaInner>? = null

)
