/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.PaginationPagination
import com.jiktan.models.UserFriendsAllOfDataInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * User Friends
 *
 * @param pagination
 * @param `data`
 */


data class UserFriends (

    @get:JsonProperty("pagination")
    val pagination: PaginationPagination? = null,

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<UserFriendsAllOfDataInner>? = null

)
