/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Available images in JPG
 *
 * @param imageUrl Image URL JPG
 */


data class UserImagesJpg (

    /* Image URL JPG */
    @get:JsonProperty("image_url")
    val imageUrl: kotlin.String? = null

)
