/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.UserImagesJpg
import com.jiktan.models.UserImagesWebp

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param jpg
 * @param webp
 */


data class UserImages (

    @get:JsonProperty("jpg")
    val jpg: UserImagesJpg? = null,

    @get:JsonProperty("webp")
    val webp: UserImagesWebp? = null

)
