/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.CharacterImages

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param images
 * @param name Entry name
 * @param type Type of resource
 * @param title Resource Name/Title
 */


data class UserFavoritesCharactersInner (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: CharacterImages? = null,

    /* Entry name */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Type of resource */
    @get:JsonProperty("type")
    val type: kotlin.String? = null,

    /* Resource Name/Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null

)
