/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param entry
 * @param score
 * @param status
 * @param episodesSeen
 * @param episodesTotal
 * @param date ISO8601 format
 */


data class UserUpdatesDataAnimeInner (

    @get:JsonProperty("entry")
    val entry: AnimeMeta? = null,

    @get:JsonProperty("score")
    val score: kotlin.Int? = null,

    @get:JsonProperty("status")
    val status: kotlin.String? = null,

    @get:JsonProperty("episodes_seen")
    val episodesSeen: kotlin.Int? = null,

    @get:JsonProperty("episodes_total")
    val episodesTotal: kotlin.Int? = null,

    /* ISO8601 format */
    @get:JsonProperty("date")
    val date: kotlin.String? = null

)
