/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeFullExternalInner
import com.jiktan.models.UserImages
import com.jiktan.models.UserProfileFullStatistics

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Transform the resource into an array.
 *
 * @param malId MyAnimeList ID
 * @param username MyAnimeList Username
 * @param url MyAnimeList URL
 * @param images
 * @param lastOnline Last Online Date ISO8601
 * @param gender User Gender
 * @param birthday Birthday Date ISO8601
 * @param location Location
 * @param joined Joined Date ISO8601
 * @param statistics
 * @param `external`
 */


data class UserProfileFull (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList Username */
    @get:JsonProperty("username")
    val username: kotlin.String? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    @get:JsonProperty("images")
    val images: UserImages? = null,

    /* Last Online Date ISO8601 */
    @get:JsonProperty("last_online")
    val lastOnline: kotlin.String? = null,

    /* User Gender */
    @get:JsonProperty("gender")
    val gender: kotlin.String? = null,

    /* Birthday Date ISO8601 */
    @get:JsonProperty("birthday")
    val birthday: kotlin.String? = null,

    /* Location */
    @get:JsonProperty("location")
    val location: kotlin.String? = null,

    /* Joined Date ISO8601 */
    @get:JsonProperty("joined")
    val joined: kotlin.String? = null,

    @get:JsonProperty("statistics")
    val statistics: UserProfileFullStatistics? = null,

    @get:JsonProperty("external")
    val `external`: kotlin.collections.List<AnimeFullExternalInner>? = null

)
