/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeMeta
import com.jiktan.models.Trailer

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param title Promo Title
 * @param entry
 * @param trailer
 */


data class WatchPromosAllOfData (

    /* Promo Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    @get:JsonProperty("entry")
    val entry: AnimeMeta? = null,

    @get:JsonProperty("trailer")
    val trailer: Trailer? = null

)
