/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.jiktan.models

import com.jiktan.models.AnimeMeta
import com.jiktan.models.WatchEpisodesAllOfEpisodes

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param entry
 * @param episodes Recent Episodes (max 2 listed)
 * @param regionLocked Region Locked Episode
 */


data class WatchEpisodesAllOfData (

    @get:JsonProperty("entry")
    val entry: AnimeMeta? = null,

    /* Recent Episodes (max 2 listed) */
    @get:JsonProperty("episodes")
    val episodes: kotlin.collections.List<WatchEpisodesAllOfEpisodes>? = null,

    /* Region Locked Episode */
    @get:JsonProperty("region_locked")
    val regionLocked: kotlin.Boolean? = null

)
