/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName"
)

package com.jiktan.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param title Episode Title
 * @param premium For MyAnimeList Premium Users
 */


data class WatchEpisodesAllOfEpisodes (

    /* MyAnimeList ID */
    @get:JsonProperty("mal_id")
    val malId: kotlin.String? = null,

    /* MyAnimeList URL */
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    /* Episode Title */
    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    /* For MyAnimeList Premium Users */
    @get:JsonProperty("premium")
    val premium: kotlin.Boolean? = null

)
