name: AniDB Delta

on:
  workflow_dispatch:
  schedule:
    # 08:00 Asia/Manila (UTC+8) → 00:00 UTC
    - cron: '0 0 * * *'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/anidb.yml'

concurrency:
  group: "build"

jobs:
  anidb-delta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch (builds)
        uses: actions/checkout@v4
        with:
          ref: builds

      - name: Retrieve anidb dump
        id: retrieve-anidb-dump
        run: |
          curl -LO -A "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" http://anidb.net/api/anime-titles.dat.gz
          curl -LO -A "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" http://anidb.net/api/anime-titles.xml.gz

          gzip -d anime-titles.dat.gz
          gzip -d anime-titles.xml.gz

          sed -i '1,3d' anime-titles.dat
          sort -t'|' -k1,1n -o anime-titles.dat{,}

          mkdir -p raw/anidb
          mv anime-titles.dat raw/anidb/titles.dat
          mv anime-titles.xml raw/anidb/titles.xml

      - name: Check for changes
        if: steps.retrieve-anidb-dump.outcome == 'success'
        id: check-changes
        run: |
          git add raw/anidb/titles.dat raw/anidb/titles.xml
          if git diff --quiet --cached raw/anidb/titles.dat raw/anidb/titles.xml; then
            echo "No changes detected in anidb dump."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]@users.noreply.github.com"

          git add raw/anidb/titles.dat raw/anidb/titles.xml
          git commit -m "AniDB Delta Update" || exit 0
          git push --force
